version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
          working_directory: logs
      - run:
          name: Build application for production
          command: npm run build
          working_directory: logs

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install logs local dependencies
          command: npm install
          working_directory: logs
      - run:
          name: Build application for production
          command: npm run build
          working_directory: logs
      - run:
          name: Install firebase-tools to logs
          command: npm install firebase-tools
          working_directory: logs
      - run:
          name: Deploy app to Firebase
          command: ./node_modules/.bin/firebase deploy --only hosting --token ${FIREBASE_TOKEN}
          working_directory: logs
workflows:
  main-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main
