version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install
          working_directory: frontend
      - run:
          name: Build application for production
          command: npm run build
          working_directory: frontend

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install frontend local dependencies
          command: npm install
          working_directory: frontend
      - run:
          name: Create .env file
          command: |
            echo "REACT_APP_SERVICE_ID = ${REACT_APP_SERVICE_ID}"
            echo "REACT_APP_PUBLIC_KEY = ${REACT_APP_PUBLIC_KEY}"
            echo "REACT_APP_TEMPLATE_ID = ${REACT_APP_TEMPLATE_ID}"
      - run:
          name: Build application for production
          command: npm run build
          working_directory: frontend
      - run:
          name: Install firebase-tools to frontend
          command: npm install firebase-tools
          working_directory: frontend
      - run:
          name: Deploy app to Firebase
          command: ./node_modules/.bin/firebase deploy --only hosting --token ${FIREBASE_TOKEN}
          working_directory: frontend
workflows:
  main-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main
